config/routes.rb
Rails.application.routes.draw do

  resources :worker_logs, only: ['index'] do
    collection do
      get "_contents"
    end
  end

  post '/parameter_sets/_delete_selected', to: 'parameter_sets#_delete_selected' if OACIS_ACCESS_LEVEL >= 1
  post '/parameter_sets/_create_runs_on_selected', to: 'parameter_sets#_create_runs_on_selected' if OACIS_ACCESS_LEVEL >= 1

  resources :runs, only: ["index"] do
    collection do
      get "_jobs_table" # for ajax, datatables
      post "_delete_selected" if OACIS_ACCESS_LEVEL >= 1
    end
  end

  resources :analyses, only: [] do
    collection do
      get "_analyses_table" # for ajax, datatables
    end
  end

  # Simulator-ParameterSet-Run relations
  simulator_actions = ["index", "show"]
  simulator_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :simulators, shallow: true, only: simulator_actions do
    collection do
      post "_sort" # for ajax, update order of the table
    end
    member do
      get "duplicate" if OACIS_ACCESS_LEVEL == 2
      get "export_runs"  # export runs in CSV
      get "_parameter_sets_list" # for ajax, datatables
      get "_analyzer_list" # for ajax, datatables
      get "_parameter_set_filters_list" # for ajax, datatables
      get "_number_of_runs" # for number of runs table
      get "_progress_overview" # for progress overview table
      get "_host_parameters_field" # for ajax, get the fields for host_parameters
      get "_default_mpi_omp" # for ajax, get the default mpi_procs and omp_threads
      get "_cancel_create_ps"
      post "save_filter" if OACIS_ACCESS_LEVEL >= 1
      patch "update_filter" if OACIS_ACCESS_LEVEL >= 1
      post "_delete_filter" if OACIS_ACCESS_LEVEL >= 1
      get "_find_filter"
    end

    parameter_set_actions = ["show"]
    parameter_set_actions += ["new", "create", "destroy"] if OACIS_ACCESS_LEVEL >= 1
    resources :parameter_sets, only: parameter_set_actions do
      collection do
        get "_create_cli" # show CLI command for bulk creation
      end
      member do
        get "duplicate" if OACIS_ACCESS_LEVEL >= 1
        get "_runs_and_analyses" # for ajax, get
        get "_runs_list" # for ajax, datatables
        get "_analyses_list" # for ajax, datatables
        get "_similar_parameter_sets_list" # for ajax, datatables
        get "_files_list" # for ajax, datatables
        get "download_result_files" # for download result files as zip
        get "_line_plot" # for line plot
        get "_scatter_plot" # for scatter plot
        get "_figure_viewer" # for figure viewer
        get "_neighbor"
      end

      run_actions = ["show"]
      run_actions += ["create"] if OACIS_ACCESS_LEVEL >= 1
      analysis_actions = ["show"]
      analysis_actions += ["create", "destroy"] if OACIS_ACCESS_LEVEL >= 1
      resources :runs, only: run_actions do
        member do
          get "_analyses_list" # for ajax, datatables
        end
        resources :analyses, only: analysis_actions do
          member do
            get "_result" # for ajax
          end
        end
      end
      resources :analyses, only: analysis_actions
    end

    analyzer_actions = ["show"]
    analyzer_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
    resources :analyzers, only: analyzer_actions do
      member do
        get "_parameters_form" # for ajax
        get "_inner_show" # for ajax, get
        get "_host_parameters_field" # for ajax, get the fields for host_parameters
        get "_default_mpi_omp" # for ajax, get the default mpi_procs and omp_threads
      end
    end
  end

  host_actions = ["index", "show"]
  host_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :hosts, only: host_actions do
    member do
      get "_check_scheduler_status" if OACIS_ACCESS_LEVEL >= 1
      get "_toggle_status" if OACIS_ACCESS_LEVEL == 2
    end
    collection do
      post "_sort" # for ajax, update order of the table
    end
  end

  host_group_actions = ["show"]
  host_group_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :host_groups, only: host_group_actions do
  end

  resources :notification_events, only: :index
  resource :oacis_setting, only: %i[edit update] if OACIS_ACCESS_LEVEL == 2

  root :to => "simulators#index"
end

app/models/host_group.rb
class HostGroup
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  has_and_belongs_to_many :hosts

  validates :name, presence: true, uniqueness: true, length: {minimum: 1}
  validates :host_ids, length: {minimum: 1}

  before_destroy :validate_destroyable

  def self.find_by_name( host_group_name )
    found = self.where(name: host_group_name).first
    raise "HostGroup #{host_group_name} is not found" unless found
    found
  end

  def destroyable?
    Run.where(status: :created, host_group: self).empty?
  end

  def validate_destroyable
    if destroyable?
      return true
    else
      errors.add(:base, "Created/Submitted Runs exist")
      throw(:abort)
    end
  end
end

app/controllers/host_groups_controller.rb
class HostGroupsController < ApplicationController

  def show
    unless HostGroup.where(id: params[:id]).exists?
      flash[:alert] = "HostGroup #{params[:id]} is not found"
      redirect_to hosts_path and return
    end
    @hg = HostGroup.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @hg = HostGroup.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @hg = HostGroup.new( permitted_host_group_params )

    respond_to do |format|
      if @hg.save
        format.html {
          redirect_to @hg, notice: 'HostGroup was successfully created.'
        }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    unless HostGroup.where(id: params[:id]).exists?
      flash[:alert] = "HostGroup #{params[:id]} is not found"
      redirect_to hosts_path and return
    end
    @hg = HostGroup.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update
    @hg = HostGroup.find(params[:id])

    respond_to do |format|
      if @hg.update_attributes(permitted_host_group_params)
        format.html {
          redirect_to @hg, notice: 'HostGroup was successfully updated.'
        }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @hg = HostGroup.find(params[:id])

    respond_to do |format|
      if @hg.destroy
        format.html { redirect_to hosts_url }
      else
        flash.now[:alert] = "Cannot destroy the HostGroup."
        format.html {render action: "show" }
      end
    end
  end

  private
  def permitted_host_group_params
    params.require(:host_group).permit(:name, host_ids: [])
  end
end

app/views/host_groups/_form.html.haml
= form_for @hg, html: {class: 'form-horizontal'} do |f|
  - error_messages = @hg.errors.full_messages
  = render partial: 'shared/error_messages', locals: {error_messages: error_messages}
  .form-group
    = f.label(:name, class: 'col-md-2 control-label')
    .col-md-3
      = f.text_field(:name, class: 'form-control')
  .form-group
    %label.col-md-2.control-label
      Hosts
    .col-md-10
      = hidden_field_tag "host_group[host_ids][]", nil
      .checkbox
        - Host.all.each do |host|
          %div
            %label{ for: dom_id(host) }
              = check_box_tag "host_group[host_ids][]", host.id.to_s, @hg.host_ids.include?(host.id), id: dom_id(host)
              = host.name
  .form-group
    .col-md-4.col-md-offset-2
      = f.submit('Save', class: 'btn btn-primary')
      = link_to('Cancel', (@hg.persisted? ? @hg : hosts_path), class: 'btn btn-default')

app/views/host_groups/_index.html.haml
.page-header
  %h1 Host Groups

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Name
      %th Hosts
      %th
  %tbody
    - host_groups.each do |hg|
      = content_tag_for :tr, hg do
        %td= link_to(hg.name, hg)
        %td
          = raw( hg.hosts.map(&:name).join('<br/>') )
        %td
          = link_to 'Delete', hg, method: :delete, data: { confirm: 'Are you sure?' }, class: 'label label-warning' if hg.destroyable? and (OACIS_ACCESS_LEVEL == 2)

- if OACIS_ACCESS_LEVEL == 2
  %a.btn.btn-primary{href: new_host_group_path} New Host Group

app/views/host_groups/edit.html.haml
.page-header
  %h1 Editing Host Group

= render 'form'

app/views/host_groups/new.html.haml
%h1 New Host Group

= render 'form'

app/views/host_groups/show.html.haml
.page-header
  %h1= "HostGroup: #{@hg.name}"

%table.table.table-striped
  %thead
  %tbody
    %tr
      %th Name
      %td= @hg.name
    %tr
      %th Hosts
      %td
        - links = @hg.hosts.map {|h| link_to(h.name, host_path(h)) }
        = raw( links.join('<br />') )

- if OACIS_ACCESS_LEVEL == 2
  = link_to 'Edit', edit_host_group_path(@hg), class: 'btn btn-info'
  = link_to 'Back to Index', hosts_path, class: 'btn btn-default'
  = link_to 'Delete', @hg, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' if @hg.destroyable?