config/routes.rb
Rails.application.routes.draw do

  resources :worker_logs, only: ['index'] do
    collection do
      get "_contents"
    end
  end

  post '/parameter_sets/_delete_selected', to: 'parameter_sets#_delete_selected' if OACIS_ACCESS_LEVEL >= 1
  post '/parameter_sets/_create_runs_on_selected', to: 'parameter_sets#_create_runs_on_selected' if OACIS_ACCESS_LEVEL >= 1

  resources :runs, only: ["index"] do
    collection do
      get "_jobs_table" # for ajax, datatables
      post "_delete_selected" if OACIS_ACCESS_LEVEL >= 1
    end
  end

  resources :analyses, only: [] do
    collection do
      get "_analyses_table" # for ajax, datatables
    end
  end

  # Simulator-ParameterSet-Run relations
  simulator_actions = ["index", "show"]
  simulator_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :simulators, shallow: true, only: simulator_actions do
    collection do
      post "_sort" # for ajax, update order of the table
    end
    member do
      get "duplicate" if OACIS_ACCESS_LEVEL == 2
      get "export_runs"  # export runs in CSV
      get "_parameter_sets_list" # for ajax, datatables
      get "_analyzer_list" # for ajax, datatables
      get "_parameter_set_filters_list" # for ajax, datatables
      get "_number_of_runs" # for number of runs table
      get "_progress_overview" # for progress overview table
      get "_host_parameters_field" # for ajax, get the fields for host_parameters
      get "_default_mpi_omp" # for ajax, get the default mpi_procs and omp_threads
      get "_cancel_create_ps"
      post "save_filter" if OACIS_ACCESS_LEVEL >= 1
      patch "update_filter" if OACIS_ACCESS_LEVEL >= 1
      post "_delete_filter" if OACIS_ACCESS_LEVEL >= 1
      get "_find_filter"
    end

    parameter_set_actions = ["show"]
    parameter_set_actions += ["new", "create", "destroy"] if OACIS_ACCESS_LEVEL >= 1
    resources :parameter_sets, only: parameter_set_actions do
      collection do
        get "_create_cli" # show CLI command for bulk creation
      end
      member do
        get "duplicate" if OACIS_ACCESS_LEVEL >= 1
        get "_runs_and_analyses" # for ajax, get
        get "_runs_list" # for ajax, datatables
        get "_analyses_list" # for ajax, datatables
        get "_similar_parameter_sets_list" # for ajax, datatables
        get "_files_list" # for ajax, datatables
        get "download_result_files" # for download result files as zip
        get "_line_plot" # for line plot
        get "_scatter_plot" # for scatter plot
        get "_figure_viewer" # for figure viewer
        get "_neighbor"
      end

      run_actions = ["show"]
      run_actions += ["create"] if OACIS_ACCESS_LEVEL >= 1
      analysis_actions = ["show"]
      analysis_actions += ["create", "destroy"] if OACIS_ACCESS_LEVEL >= 1
      resources :runs, only: run_actions do
        member do
          get "_analyses_list" # for ajax, datatables
        end
        resources :analyses, only: analysis_actions do
          member do
            get "_result" # for ajax
          end
        end
      end
      resources :analyses, only: analysis_actions
    end

    analyzer_actions = ["show"]
    analyzer_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
    resources :analyzers, only: analyzer_actions do
      member do
        get "_parameters_form" # for ajax
        get "_inner_show" # for ajax, get
        get "_host_parameters_field" # for ajax, get the fields for host_parameters
        get "_default_mpi_omp" # for ajax, get the default mpi_procs and omp_threads
      end
    end
  end

  host_actions = ["index", "show"]
  host_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :hosts, only: host_actions do
    member do
      get "_check_scheduler_status" if OACIS_ACCESS_LEVEL >= 1
      get "_toggle_status" if OACIS_ACCESS_LEVEL == 2
    end
    collection do
      post "_sort" # for ajax, update order of the table
    end
  end

  host_group_actions = ["show"]
  host_group_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :host_groups, only: host_group_actions do
  end

  resources :notification_events, only: :index
  resource :oacis_setting, only: %i[edit update] if OACIS_ACCESS_LEVEL == 2

  root :to => "simulators#index"
end

app/models/analyzer.rb
class Analyzer
  include Mongoid::Document
  include Mongoid::Timestamps
  include Executable

  field :name, type: String
  field :type, type: Symbol
  field :auto_run, type: Symbol, default: :no
  field :files_to_copy, type: String, default: '*'
  field :description, type: String
  field :to_be_destroyed, type: Boolean, default: false

  embeds_many :parameter_definitions
  belongs_to :simulator
  has_many :analyses

  ## fields for auto run
  belongs_to :auto_run_submitted_to, class_name: "Host"
  belongs_to :auto_run_host_group, class_name: "HostGroup"

  default_scope ->{ where(to_be_destroyed: false) }

  validates :name, presence: true, uniqueness: {scope: [:simulator, :to_be_destroyed] }, format: {with: /\A\w+\z/}, unless: :to_be_destroyed
  validates :type, presence: true, 
                   inclusion: {in: [:on_run, :on_parameter_set]}
  validates :auto_run, inclusion: {in: [:yes, :no, :first_run_only]}
  validate :auto_run_submitted_to_is_in_executable_on

  accepts_nested_attributes_for :parameter_definitions, allow_destroy: true

  public
  def parameter_definition_for(key)
    found = self.parameter_definitions.detect do |pd|
      pd.key == key
    end
    found
  end

  public
  def analyzer_versions
    # output should look like follows
    # [{"_id"=>"v1",
    #   "oldest_started_at"=>2014-04-19 02:10:08 utc,
    #   "latest_started_at"=>2014-04-20 02:10:08 utc,
    #   "count" => {:finished => 2} },
    #  {"_id"=>"v2",
    #   "oldest_started_at"=>2014-04-19 02:10:08 utc,
    #   "latest_started_at"=>2014-04-21 02:10:08 utc,
    #   "count"=> {:finished => 2, :failed => 1} }]
    query = Analysis.where(analyzer: self).exists(started_at: true).selector
    aggregated = Analysis.collection.aggregate([
      {'$match' => query },
      { '$group' => {'_id' => { version: '$analyzer_version', status: '$status'},
                     oldest_started_at: { '$min' => '$started_at'},
                     latest_started_at: { '$max' => '$started_at'},
                     count: {'$sum' => 1}
                     }}])

    anl_versions = {}
    aggregated.each do |h|
      version = h['_id']['version']
      merged = (anl_versions[version] or {})
      if merged['oldest_started_at'].nil? or merged['oldest_started_at'] > h['oldest_started_at']
        merged['oldest_started_at'] = h['oldest_started_at']
      end
      if merged['latest_started_at'].nil? or merged['latest_started_at'] < h['latest_started_at']
        merged['latest_started_at'] = h['latest_started_at']
      end
      merged['count'] ||= {}
      status = h['_id']['status']
      merged['count'][status] = h['count']
      anl_versions[version] = merged
    end

    anl_versions.map {|key,val| val['version'] = key; val }.sort_by {|a| a['latest_started_at']}
  end

  def discard
    update_attribute(:to_be_destroyed, true)
    set_lower_submittable_to_be_destroyed
  end

  def destroyable?
    analyses.unscoped.empty?
  end

  def set_lower_submittable_to_be_destroyed
    analyses.update_all(to_be_destroyed: true)
    reload
  end

  private
  def auto_run_submitted_to_is_in_executable_on
    return if auto_run == :no
    unless executable_on.where(id: auto_run_submitted_to).first
       errors.add(:auto_run_submitted_to, "is not included in executable hosts")
    end
  end
end

app/controllers/analyzers_controller.rb
class AnalyzersController < ApplicationController

  def show
    unless Analyzer.where(id: params[:id]).exists?
      flash[:alert] = "Analyzer #{params[:id]} is not found"
      redirect_to root_path and return
    end
    @analyzer = Analyzer.find(params[:id])

    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    simulator = Simulator.find(params[:simulator_id])
    @analyzer = simulator.analyzers.build

    respond_to do |format|
      format.html
      format.json { render json: @analyzer }
    end
  end

  def edit
    unless Analyzer.where(id: params[:id]).exists?
      flash[:alert] = "Analyzer #{params[:id]} is not found"
      redirect_to root_path and return
    end
    @analyzer = Analyzer.find(params[:id])
  end

  def create
    simulator = Simulator.find(params[:simulator_id])
    @analyzer = simulator.analyzers.build(permitted_analyzer_params)

    respond_to do |format|
      if @analyzer.save
        format.html { redirect_to @analyzer, notice: 'Analyzer was successfully created.' }
        format.json { render json: @analyzer, status: :created, location: @analyzer }
      else
        format.html { render action: "new" }
        format.json { render json: @analyzer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    unless Analyzer.where(id: params[:id]).exists?
      flash[:alert] = "Analyzer #{params[:id]} is not found"
      redirect_to root_path and return
    end
    @analyzer = Analyzer.find(params[:id])

    respond_to do |format|
      if @analyzer.update_attributes(permitted_analyzer_params)
        format.html { redirect_to @analyzer, notice: 'Analyzer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @analyzer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    analyzer = Analyzer.find(params[:id])
    simulator = analyzer.simulator
    analyzer.discard

    respond_to do |format|
      format.json { head :no_content }
      format.js
      format.html { redirect_to simulator_path(simulator) }
    end
  end

  # GET /analyzers/:id/_parameters_form
  def _parameters_form
    analyzer = Analyzer.find(params[:id])

    render partial: 'analyses/parameters_form', layout: false, locals: {analyzer: analyzer}
  end

  def _inner_show
    analyzer = Analyzer.find(params[:id])
    render partial: "inner_show", locals: {analyzer: analyzer}
  end

  def _host_parameters_field
    azr = Analyzer.find(params[:id])
    host = Host.where(id: params[:host_id]).first
    render partial: "analyses/host_parameter_fields", locals: {analyzer: azr, host: host}
  end

  def _default_mpi_omp
    azr = Analyzer.find(params[:id])
    host = Host.where(id: params[:host_id]).first
    host_id = host ? host.id.to_s : nil
    mpi = azr.default_mpi_procs[host_id] || 1
    omp = azr.default_omp_threads[host_id] || 1
    data = {'mpi_procs' => mpi, 'omp_threads' => omp}
    render json: data
  end

  private
  def permitted_analyzer_params
    return {} unless params[:analyzer].present?
    azr_params = params.require(:analyzer)
      .permit(:name,
              :type,
              :command,
              :description,
              :auto_run,
              :files_to_copy,
              :print_version_command,
              :simulator,
              :support_input_json,
              :support_mpi,
              :support_omp,
              :pre_process_script,
              :local_pre_process_script,
              :auto_run_submitted_to,
              :auto_run_host_group,
              parameter_definitions_attributes: [[:id, :key, :type, :default, :options, :description, :_destroy]],
              executable_on_ids: []
             )
    if submitted_to_is_host_group?(azr_params)
      azr_params[:auto_run_host_group] = azr_params[:auto_run_submitted_to]
      azr_params[:auto_run_submitted_to] = nil
    end
    azr_params
  end

  def submitted_to_is_host_group?(azr_params)
    host_id = azr_params[:auto_run_submitted_to]
    host_id.present? && HostGroup.where(id: host_id).present?
  end
end

app/views/analyzers/_about.html.haml
- if analyzer.description.present?
  %div.well
    = markdown(analyzer.description)

%table.table.table-striped.table-condensed
  %thead
  %tbody
    %tr
      %th ID
      %td= analyzer.id
    %tr
      %th Type
      %td= analyzer.type
    %tr
      %th Auto-Run Flag
      %td= analyzer.auto_run
    %tr
      %th Parameter Input Type
      %td= analyzer.support_input_json ? "JSON" : "Arguments"
    %tr
      %th Files to Copy
      %td= raw( analyzer.files_to_copy.chomp.gsub("\n", '<br />') )
    %tr
      %th Support MPI
      %td= analyzer.support_mpi ? "Yes" : "No"
    %tr
      %th Support OMP
      %td= analyzer.support_omp ? "Yes" : "No"
    %tr
      %th Executable On
      %td= raw( analyzer.executable_on.map {|host| h(host.name) }.join('<br />') )
    %tr
      %th Host(Group) for Auto-Run
      %td= analyzer.auto_run_submitted_to.try(:name) || analyzer.auto_run_host_group.try(:name)

- if analyzer.parameter_definitions.present?
  %h3 Defined Parameters
  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th.col-md-2
        %th.col-md-2 Type
        %th.col-md-2 Default
        %th.col-md-6 Description
    %tbody
      - analyzer.parameter_definitions.each do |pd|
        %tr
          %th= pd.key
          %td= pd.type
          %td= pd.default || '-'
          - if pd.type == 'Selection'
            %td= "#{pd.description} [#{pd.options_array.join(', ')}]"
          - else
            %td= pd.description ? pd.description : "-"

%h3 Commands
%ul
  %li
    Pre-process Script
    %br
    %pre
      = analyzer.pre_process_script
  %li
    Local Pre-process Script
    %br
    %pre
      = analyzer.local_pre_process_script
  %li
    Analyzer Command
    %br
    %pre
      = analyzer.command
  %li
    Print-version Command
    %br
    %pre
      = analyzer.print_version_command

%h3 List of Analyzer Versions
%table.table.table-striped.table-condensed#analyzer_version_table
  %thead
    %tr
      %th Version
      %th Oldest started_at
      %th Latest started_at
      %th= raw(status_label(:finished))
      %th= raw(status_label(:failed))
      %th CLI
  %tbody
    - analyzer.analyzer_versions.each do |anl_version|
      %tr
        %td= anl_version['version'] || "---"
        - d = anl_version['oldest_started_at']
        %td= d ? "#{d} (#{distance_to_now_in_words(d)})" : '---'
        - d = anl_version['latest_started_at']
        %td= d ? "#{d} (#{distance_to_now_in_words(d)})" : '---'
        %td= anl_version['count'][:finished].to_i
        %td= anl_version['count'][:failed].to_i
        %td
          %i.fa.fa-cog.clickable#show_cli{data: ""+raw(render partial: "version_dialog", locals: {azr: analyzer, version: anl_version['version']})}

:css
  .modal-vertical-centered {
    transform: translate(0, 50%) !important;
    -ms-transform: translate(0, 50%) !important; /* IE 9 */
    -webkit-transform: translate(0, 50%) !important; /* Safari and Chrome */
  }

#version_dialog_modal.modal.large.fade
  .modal-dialog.modal-vertical-centered
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal"}
          &times;
        %h4.modal-title
          CLI
      .modal-body.large#version_dialog
      .modal-footer
        %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
          Close

:javascript
  $("#analyzer_version_table #show_cli").on("click", function(){
    $('#version_dialog_modal').modal("show");
  });
  $("#version_dialog_modal").on('show.bs.modal', function (event) {
    $('#version_dialog').append($("#analyzer_version_table #show_cli").attr("data"));
  });
  $("#version_dialog_modal").on('hidden.bs.modal', function (event) {
    $('#version_dialog').empty();
  });

- if OACIS_ACCESS_LEVEL == 2
  = link_to 'Edit', edit_analyzer_path(analyzer), class: 'btn btn-info'
  = link_to 'Delete', analyzer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning'
= link_to 'Show in JSON', analyzer_path(analyzer, format: :json), class: 'btn btn-default'

app/views/analyzers/_form.html.haml
- path = analyzer.persisted? ? analyzer : [simulator, analyzer]
= form_for path, html: {class: ['form-horizontal','wide-tooltip']}, builder: ApplicationFormBuilder do |f|
  = render partial: 'shared/error_messages', locals: {error_messages: analyzer.errors.full_messages}
  - has_child = analyzer.analyses.present?
  .form-group
    = f.label_c(:name)
    .col-md-3
      = f.text_field(:name, class: 'text_field form-control', data: tooltip_data(:analyzer,:name), disabled: has_child)
  .form-group
    = f.label_c(:type)
    .col-md-3
      = f.select(:type, ["on_run", "on_parameter_set"], {}, class: 'form-control', data: tooltip_data(:analyzer,:type), disabled: has_child)
  #parameters_form.form-group
    = raw(label_c('Definition of Parameters'))
    .col-md-10
      = f.fields_for :parameter_definitions do |builder|
        = render partial: 'executable/parameter_definition_fields', locals: {f: builder, disabled: has_child}
      - unless has_child
        = link_to_add_fields "Add Parameter", f, :parameter_definitions, 'executable/parameter_definition_fields'
  .form-group
    = f.label_c(:pre_process_script)
    .col-md-6
      = f.text_area(:pre_process_script, rows: 3, class: 'form-control', data: tooltip_data(:analyzer,:pre_process_script))
  .form-group
    = f.label_c(:local_pre_process_script)
    .col-md-6
      = f.text_area(:local_pre_process_script, rows: 1, class: 'form-control', data: tooltip_data(:analyzer,:local_pre_process_script))
  .form-group
    = f.label_c(:command)
    .col-md-6
      = f.text_field(:command, class: 'form-control', data: tooltip_data(:analyzer,:command))
  .form-group
    = f.label_c(:print_version_command)
    .col-md-6
      = f.text_field(:print_version_command, class: 'form-control', data: tooltip_data(:analyzer,:print_version_command))
  .form-group
    = f.label_c(:support_input_json, "Input type")
    .col-md-3
      = f.select(:support_input_json, {"Argument" => false, "JSON" => true}, {}, class: 'form-control', data: tooltip_data(:analyzer,:input_type))
  .form-group
    = f.label_c(:files_to_copy)
    .col-md-6
      = f.text_area(:files_to_copy, rows:2, class: 'form-control', data: tooltip_data(:analyzer,:files_to_copy))
  .form-group
    = f.label_c(:support_mpi)
    .col-md-2
      .checkbox
        %label
          = f.check_box(:support_mpi, data: tooltip_data(:analyzer,:support_mpi))
  .form-group
    = f.label_c(:support_omp)
    .col-md-2
      .checkbox
        %label
          = f.check_box(:support_omp, data: tooltip_data(:analyzer,:support_omp))
  .form-group
    = f.label_c(:auto_run)
    .col-md-3
      = f.select(:auto_run, [:no,:yes,:first_run_only], {}, id: "auto_run", class: 'form-control', data: tooltip_data(:analyzer,:auto_run))
  .form-group
    = f.label_c(:description)
    .col-md-6
      = f.text_area(:description, rows: 5, class: 'form-control', data: tooltip_data(:analyzer,:description))
  .form-group
    = raw(label_c('Executable_on'))
    .col-md-10
      = hidden_field_tag "analyzer[executable_on_ids][]", nil
      - Host.all.each do |host|
        .checkbox
          %label{ for: dom_id(host) }
            = check_box_tag "analyzer[executable_on_ids][]", host.id.to_s, analyzer.executable_on_ids.include?(host.id), id: dom_id(host)
            = host.name
  .form-group
    = f.label_c(:auto_run_submitted_to, "Host for Auto Run")
    .col-md-3
      - selected_id = analyzer.auto_run_submitted_to.try(:id).try(:to_s) || analyzer.auto_run_host_group.try(:id).try(:to_s)
      - opts = (Host.all.map {|h| [h.name, h.id]}) + (HostGroup.all.map {|hg| ["(HostGroup) #{hg.name}", hg.id]})
      - host_options = options_for_select( opts, selected: selected_id)
      = f.select(:auto_run_submitted_to, host_options, {}, class: 'form-control', data: tooltip_data(:analyzer, :host_for_auto_run))
  .form-group
    .col-md-3.col-md-offset-2
      = f.submit(class: 'btn btn-primary')
      = link_to('Cancel', simulator_path(simulator, anchor: '!tab-about'), class: 'btn btn-default')

:javascript
  $(function() {
    $('select#analyzer_type').change(function() {
      const selected = $(this).val();
      const auto_run = $('select#auto_run');
      if(selected == "on_run") {
        if( auto_run.children('[value=first_run_only]').size() == 0 ) {
          auto_run.append( $('<option>').val('first_run_only').text('first_run_only') );
        }
      }
      else if(selected == "on_parameter_set") {
        auto_run.children('[value=first_run_only]').remove();
      }
    });
    $('select#analyzer_type').trigger('change');
  });

app/views/analyzers/_inner_show.html.haml
= render "about", analyzer: analyzer

app/views/analyzers/_link_to_doc.html.haml
%a{href: "http://crest-cassia.github.io/oacis/en/configuring_analyzer.html", target: '_blank'}
  %small
    %i.fa.fa-question-circle-o

app/views/analyzers/_version_dialog.html.haml
%h3 CLI commands for #{azr.name}

%h3 Destroy analyses

%ul
  %li
    analyzer_version:#{version}
    %br
    %pre ./bin/oacis_cli destroy_analyses -a #{azr.id} -q analyzer_version:#{version}
  %li
    analyzer_version:#{version}, status:
    %span.label.label-success.status-label
      finished
    %br
    %pre ./bin/oacis_cli destroy_analyses -a #{azr.id} -q analyzer_version:#{version} status:finished
  %li
    analyzer_version:#{version}, status:
    %span.label.label-danger.status-label
      failed
    %br
    %pre ./bin/oacis_cli destroy_analyses -a #{azr.id} -q analyzer_version:#{version} status:failed

%h3 Replace analyses

%ul
  %li
    analyzer_version:#{version}
    %br
    %pre ./bin/oacis_cli replace_analyses -a #{azr.id} -q analyzer_version:#{version}
  %li
    analyzer_version:#{version}, status:
    %span.label.label-success.status-label
      finished
    %br
    %pre ./bin/oacis_cli replace_analyses -a #{azr.id} -q analyzer_version:#{version} status:finished
  %li
    analyzer_version:#{version}, status:
    %span.label.label-danger.status-label
      failed
    %br
    %pre ./bin/oacis_cli replace_analyses -a #{azr.id} -q analyzer_version:#{version} status:failed

app/views/analyzers/destroy.js.haml
reload_analyzers_table();

app/views/analyzers/edit.html.haml
.page-header
  %h1
    Edit Analyzer
    = render partial: 'link_to_doc'

= render "form", simulator: @analyzer.simulator, analyzer: @analyzer

app/views/analyzers/new.html.haml
.page-header
  %h1
    New Analyzer
    = render partial: 'link_to_doc'
= render "form", simulator: @analyzer.simulator, analyzer: @analyzer

app/views/analyzers/show.html.haml
= render partial: "shared/breadcrumb", locals: {links: breadcrumb_links_for(@analyzer)}

.page-header
  %h1= @analyzer.name

= render "about", analyzer: @analyzer