config/routes.rb
Rails.application.routes.draw do

  resources :worker_logs, only: ['index'] do
    collection do
      get "_contents"
    end
  end

  post '/parameter_sets/_delete_selected', to: 'parameter_sets#_delete_selected' if OACIS_ACCESS_LEVEL >= 1
  post '/parameter_sets/_create_runs_on_selected', to: 'parameter_sets#_create_runs_on_selected' if OACIS_ACCESS_LEVEL >= 1

  resources :runs, only: ["index"] do
    collection do
      get "_jobs_table" # for ajax, datatables
      post "_delete_selected" if OACIS_ACCESS_LEVEL >= 1
    end
  end

  resources :analyses, only: [] do
    collection do
      get "_analyses_table" # for ajax, datatables
    end
  end

  # Simulator-ParameterSet-Run relations
  simulator_actions = ["index", "show"]
  simulator_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :simulators, shallow: true, only: simulator_actions do
    collection do
      post "_sort" # for ajax, update order of the table
    end
    member do
      get "duplicate" if OACIS_ACCESS_LEVEL == 2
      get "export_runs"  # export runs in CSV
      get "_parameter_sets_list" # for ajax, datatables
      get "_analyzer_list" # for ajax, datatables
      get "_parameter_set_filters_list" # for ajax, datatables
      get "_number_of_runs" # for number of runs table
      get "_progress_overview" # for progress overview table
      get "_host_parameters_field" # for ajax, get the fields for host_parameters
      get "_default_mpi_omp" # for ajax, get the default mpi_procs and omp_threads
      get "_cancel_create_ps"
      post "save_filter" if OACIS_ACCESS_LEVEL >= 1
      patch "update_filter" if OACIS_ACCESS_LEVEL >= 1
      post "_delete_filter" if OACIS_ACCESS_LEVEL >= 1
      get "_find_filter"
    end

    parameter_set_actions = ["show"]
    parameter_set_actions += ["new", "create", "destroy"] if OACIS_ACCESS_LEVEL >= 1
    resources :parameter_sets, only: parameter_set_actions do
      collection do
        get "_create_cli" # show CLI command for bulk creation
      end
      member do
        get "duplicate" if OACIS_ACCESS_LEVEL >= 1
        get "_runs_and_analyses" # for ajax, get
        get "_runs_list" # for ajax, datatables
        get "_analyses_list" # for ajax, datatables
        get "_similar_parameter_sets_list" # for ajax, datatables
        get "_files_list" # for ajax, datatables
        get "download_result_files" # for download result files as zip
        get "_line_plot" # for line plot
        get "_scatter_plot" # for scatter plot
        get "_figure_viewer" # for figure viewer
        get "_neighbor"
      end

      run_actions = ["show"]
      run_actions += ["create"] if OACIS_ACCESS_LEVEL >= 1
      analysis_actions = ["show"]
      analysis_actions += ["create", "destroy"] if OACIS_ACCESS_LEVEL >= 1
      resources :runs, only: run_actions do
        member do
          get "_analyses_list" # for ajax, datatables
        end
        resources :analyses, only: analysis_actions do
          member do
            get "_result" # for ajax
          end
        end
      end
      resources :analyses, only: analysis_actions
    end

    analyzer_actions = ["show"]
    analyzer_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
    resources :analyzers, only: analyzer_actions do
      member do
        get "_parameters_form" # for ajax
        get "_inner_show" # for ajax, get
        get "_host_parameters_field" # for ajax, get the fields for host_parameters
        get "_default_mpi_omp" # for ajax, get the default mpi_procs and omp_threads
      end
    end
  end

  host_actions = ["index", "show"]
  host_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :hosts, only: host_actions do
    member do
      get "_check_scheduler_status" if OACIS_ACCESS_LEVEL >= 1
      get "_toggle_status" if OACIS_ACCESS_LEVEL == 2
    end
    collection do
      post "_sort" # for ajax, update order of the table
    end
  end

  host_group_actions = ["show"]
  host_group_actions += ["new", "create", "edit", "update", "destroy"] if OACIS_ACCESS_LEVEL == 2
  resources :host_groups, only: host_group_actions do
  end

  resources :notification_events, only: :index
  resource :oacis_setting, only: %i[edit update] if OACIS_ACCESS_LEVEL == 2

  root :to => "simulators#index"
end

app/controllers/parameter_sets_controller.rb
require 'zip'

class ParameterSetsController < ApplicationController

  def show
    unless ParameterSet.where(id: params[:id]).exists?
      flash[:alert] = "ParameterSet #{params[:id]} is not found"
      redirect_to root_path and return
    end
    @param_set = ParameterSet.find(params[:id])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    unless Simulator.where(id: params[:simulator_id]).exists?
      flash[:alert] = "Simulator #{params[:simulator_id]} is not found"
      redirect_to root_path and return
    end
    simulator = Simulator.find(params[:simulator_id])
    v = {}
    simulator.parameter_definitions.each do |defn|
      v[defn.key] = defn.default unless defn.default.nil?
    end
    @param_set = simulator.parameter_sets.build(v: v)
  end

  def duplicate
    unless ParameterSet.where(id: params[:id]).exists?
      flash[:alert] = "ParameterSet #{params[:id]} is not found"
      redirect_to root_path and return
    end
    base_ps = ParameterSet.find(params[:id])
    simulator = base_ps.simulator
    @param_set = simulator.parameter_sets.build(v: base_ps.v)
    render :new
  end

  MAX_CREATION_SIZE = 10000
  def create
    simulator = Simulator.find(params[:simulator_id])
    @num_runs = params[:num_runs].to_i

    previous_num_ps = simulator.parameter_sets.count
    previous_num_runs = simulator.runs.count

    permitted_params = params.permit(v: params[:v].keys)
    @param_set = simulator.parameter_sets.build(permitted_params)
    # this run is not saved, but used when rendering new
    if @num_runs > 0
      run_params = permitted_run_params(params)

      @run = @param_set.runs.build(run_params)
      unless @run.valid?
        render action: "new"
        return
      end
    end

    # create SaveTask
    casted = {}
    simulator.parameter_definitions.each do |defn|
      key = defn.key
      parameters = params[:v].dup
      if parameters[key].present? and defn.type != "Object" and defn.type != "Selection"
        casted[key] = CSV.parse(parameters[key], liberal_parsing: true)[0]&.map {|x|
          ParametersUtil.cast_value(x.strip, defn.type)
        }
      elsif defn.type == "Selection"
        casted[key] = parameters[key]
      else
        casted[key] = [parameters.has_key?(key) ? ParametersUtil.cast_value(parameters[key], defn.type) : defn.default]
      end
      if casted[key].any? {|x| x == nil }
        @param_set.errors.add(:base, "Invalid parameter is given for #{key}")
        render action: "new"
        return
      end
      casted[key] = casted[key].uniq.sort
    end
    if MAX_CREATION_SIZE < casted.values.map(&:size).inject(1, :*)
      flash[:alert] = "You cannot create more than #{MAX_CREATION_SIZE} ParameterSets at once."
      render action: "new"
      return
    end
    task = simulator.save_tasks.build(param_values: casted, run_params: run_params.to_h, num_runs: @num_runs)

    created = task.make_ps_in_batches(true)

    if task.remaining?
      task.save!
      flash[:notice] = "#{task.creation_size} ParameterSets and #{task.creation_size*@num_runs} runs are being created"
      redirect_to simulator
    else
      num_created_ps = simulator.reload.parameter_sets.count - previous_num_ps
      num_created_runs = simulator.runs.count - previous_num_runs
      if num_created_ps == 0 and num_created_runs == 0
        @param_set.errors.add(:base, "Identical ParameterSet already exists. No ParameterSet was created.")
        render action: "new"
      else
        flash[:notice] = "#{num_created_ps} ParameterSets and #{num_created_runs} runs were created"
        if created.size == 1
          redirect_to created.first
        else
          redirect_to simulator
        end
      end
    end
  end

  def _delete_selected
    selected_ps_ids = params[:id_list].to_s.split(",")

    cnt = 0
    sim = nil
    selected_ps_ids.each do |ps_id|
      ps = ParameterSet.where(id: ps_id).first
      if ps.present?
        sim ||= ps.simulator
        ps.discard
        cnt += 1
      end
    end

    if cnt == selected_ps_ids.size
      flash[:notice] = "#{cnt} parameter set#{cnt > 1 ? 's were' : ' was'} successfully deleted"
    elsif cnt == 0
      flash[:alert] = "No parameter sets were deleted"
    else
      flash[:alert] = "#{cnt} parameter set#{cnt > 1 ? 's were' : ' was'} deleted (your request was #{selected_ps_ids.size} deletion)"
    end

    redirect_to(sim || root_path)
  end

  def _create_runs_on_selected
    param_set_ids = params[:ps_ids].to_s.split(",")
    num_runs = params[:num_runs].to_i
    raise 'params[:num_runs] is invalid' unless num_runs > 0

    num_created = 0
    run_params = permitted_run_params(params)
    param_set_ids.each do |ps_id|
      param_set = ParameterSet.where(id: ps_id).first
      next unless param_set.present?
      num_runs.times do |i|
        run = param_set.runs.build(run_params)
        num_created += 1 if run.save
      end
    end

    if num_created > 0
      flash[:notice] = "#{num_created} run#{num_created > 1 ? 's were' : ' was'} successfully created"
    else
      flash[:alert] = "No runs were created"
    end

    redirect_back(fallback_location: runs_path)
  end

  private
  def permitted_run_params(params)
    if params[:run].present?
      if params[:run]["submitted_to"].present?
        id = params[:run]["submitted_to"]
        if Host.where(id: id).exists?
          host_param_keys = Host.find(id).host_parameter_definitions.map(&:key)
          params.require(:run).permit(:mpi_procs, :omp_threads, :priority, :submitted_to, host_parameters: host_param_keys)
        elsif HostGroup.where(id: id).exists?
          modify_params_for_host_group_submission
          params.require(:run).permit(:mpi_procs, :omp_threads, :priority, :host_group)
        end
      else
        params.require(:run).permit(:mpi_procs, :omp_threads, :priority)
      end
    else
      {}
    end
  end

  def modify_params_for_host_group_submission
    params[:run]["host_group"] = params[:run]["submitted_to"]
    params[:run].delete("submitted_to")
  end

  public
  def _create_cli
    simulator = Simulator.find(params[:simulator_id])
    parameters = params[:v].dup

    casted_parameters = {}
    simulator.parameter_definitions.each do |defn|
      key = defn.key
      casted = nil
      if defn.type == "Selection"
        casted = parameters[key]
      elsif parameters[key] and JSON.is_not_json?(parameters[key]) and parameters[key].include?(',')
        casted = parameters[key].split(',').map {|x|
          ParametersUtil.cast_value( x.strip, defn["type"] )
        }.compact.uniq
      else
        casted = parameters.has_key?(key) ? ParametersUtil.cast_value(parameters[key],defn["type"]) : defn["default"]
      end
      casted_parameters[key] = casted
    end
    ps_json_escaped = casted_parameters.to_json.gsub("'","'\\\\''")

    cmd = "./bin/oacis_cli create_parameter_sets -s #{simulator.id} -i '#{ps_json_escaped}'"

    num_runs = params[:num_runs].to_i
    if num_runs > 0
      run_option = {}
      run_option[:num_runs] = num_runs
      run_option[:mpi_procs] = params[:run][:mpi_procs].to_i
      run_option[:omp_threads] = params[:run][:omp_threads].to_i
      run_option[:priority] = params[:run][:priority].to_i
      run_option[:submitted_to] = params[:run][:submitted_to]
      run_option[:host_parameters] = params[:run][:host_parameters]
      run_option_escaped = run_option.to_json.gsub("'", "'\\\\''")
      cmd += " -r '#{run_option_escaped}'"
    end

    cmd += " -o ps.json"

    render plain: cmd
  end

  def destroy
    @ps = ParameterSet.find(params[:id])
    simulator = Simulator.find(@ps.simulator_id)
    @ps.discard

    respond_to do |format|
      format.json { head :no_content }
      format.js
      format.html { redirect_to simulator_path(simulator) }
    end
  end

  def _runs_and_analyses
    param_set = ParameterSet.find(params[:id])
    render partial: "inner_table", locals: {parameter_set: param_set}
  end

  def _runs_list
    param_set = ParameterSet.find(params[:id])
    render json: RunsListDatatable.new(param_set.runs, view_context)
  end

  def _analyses_list
    parameter_set = ParameterSet.find(params[:id])
    render json: AnalysesListDatatable.new(parameter_set.analyses, view_context)
  end

  def _similar_parameter_sets_list
    base_ps = ParameterSet.find(params[:id])
    keys = base_ps.simulator.parameter_definitions.map(&:key)
    selectors = keys.map {|key| base_ps.parameter_sets_with_different(key).selector }
    parameter_sets = ParameterSet.or(*selectors)
    num_ps_total = base_ps.simulator.parameter_sets.count
    render json: ParameterSetsListDatatable.new(parameter_sets, keys, view_context, num_ps_total, base_ps)
  end

  def _files_list
    param_set = ParameterSet.find(params[:id])
    render json: FilesListDatatable.new(param_set.runs.where(status: :finished), view_context)
  end

  def download_result_files
    param_set = ParameterSet.find(params[:id])
    file_name = params[:file_name]

    io = StringIO.new
    io.set_encoding(Encoding::CP932)
    Zip::OutputStream.write_buffer(io) do |zos|
      param_set.runs.where(status: :finished).map do |run|
        pathname = run.result_paths.select {|result_path| result_path.fnmatch?("*/#{file_name}") }.first
        zos.put_next_entry("#{run.id}_#{file_name}")
        buf = File.open(pathname) {|file| file.read }
        zos.write(buf)
      end
    end

    send_data io.string, filename: "#{file_name}.zip", type: :zip
  end

  def _line_plot
    ps = ParameterSet.find(params[:id])

    x_axis_key = params[:x_axis_key]
    irrelevant_keys = params[:irrelevants].split(',')

    series = (params[:series] != x_axis_key) ? params[:series] : nil
    if series.present?
      ps_array = ps.parameter_sets_with_different(series, irrelevant_keys)
        .uniq {|ps| ps.v[series] }
        .reverse # reverse the order so that the series are displayed in descending order

app/views/parameter_sets/_analyses.html.haml
= render partial: 'shared/analyses', locals: {parameter_set: parameter_set}

- sim = parameter_set.simulator
- azrs = sim.analyzers_on_parameter_set
- if (OACIS_ACCESS_LEVEL >= 1) and azrs.exists?
  %h3 Create Analysis
  - anl = parameter_set.analyses.build
  = form_for( anl, :url => parameter_set_analyses_path(parameter_set), html: {class: 'form-horizontal'}, remote: true ) do |f|
    .form-group
      = f.label :analyzer, class: 'col-md-2 control-label'
      .col-md-3
        = f.select :analyzer, azrs.map { |x| [x.name, x.to_param] }, {}, {class: 'form-control', id: 'analysis_form_analyzer'}
    %div#analysis_parameters_form
    .form-group
      .col-md-2.col-md-offset-2
        = f.submit "Analyze", :class => 'btn btn-primary'
#analyses_list_modal.modal.large.fade
  .modal-dialog.modal-vertical-centered
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal"}
          &times;
        %h4.modal-title
      .modal-body.large#analyses_list_modal_page
      .modal-footer
        %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
          Close

:javascript
  $(function() {
    const update_analysis_mpi_omp_fields = function(analyzer_id, host_id) {
      const mpi_field = $('input#analysis_mpi_procs');
      const omp_field = $('input#analysis_omp_threads');
      if( mpi_field.size() + omp_field.size() == 0 ) return;
      let url = "#{_default_mpi_omp_analyzer_url(':analyzer_id')}.json" + "?host_id=" + host_id;
      url = url.replace(':analyzer_id', analyzer_id);
      $.get(url, function(data) {
        if( mpi_field.size() > 0 ) { mpi_field.val(data['mpi_procs']); }
        if( omp_field.size() > 0 ) { omp_field.val(data['omp_threads']); }
      });
    }
    const update_host_parameters = function(analyzer_id, host_id) {
      let url = "#{_host_parameters_field_analyzer_url(':analyzer_id')}" + "?host_id=" + host_id;
      url = url.replace(':analyzer_id', analyzer_id);
      $.get(url, function(data) {
        $('#analysis_host_parameters').html(data);
      });
    }
    const analyzer_field = $('#analysis_form_analyzer')
    analyzer_field.change(function(){
      const analyzer_id = $(this).val();
      $.get("#{_parameters_form_analyzer_path(':analyzer_id')}".replace(':analyzer_id',analyzer_id), function(data) {
        $('#analysis_parameters_form').html(data);
        const submitted_to = $('#analysis_parameters_form select#analysis_submitted_to');
        submitted_to.change(function() {
          const host_id = $(this).val();
          update_analysis_mpi_omp_fields( analyzer_id, host_id );
          update_host_parameters( analyzer_id, host_id );
        });
        submitted_to.trigger('change');
      });
    });
    if( $('#analysis_form_analyzer').length > 0 ) {
      analyzer_field.trigger('change');
    }
  });

- if parameter_set.analyses.present?
  %h2 Results
- parameter_set.analyses.where(status: :finished).each do |anl|
  %hr
  %h3= "Result of Analysis: #{anl.analyzer.name}"
  = link_to(anl.id,anl)
  - if anl.parameters.present?
    = render partial: "shared/parameters_table", locals: {parameters_hash: anl.parameters}
  = render partial: "shared/results", locals: {result: anl.result, result_paths: anl.result_paths, archived_result_path: anl.archived_result_path }

app/views/parameter_sets/_files.html.haml
- first_run = @param_set.runs.where(status: :finished).first
- file_name_options = first_run&.result_paths&.map(&:basename)&.reject {|result_path| result_path.directory? || result_path.basename.to_s == "#{first_run.id.to_s}_xsub.sh" }

%h3 List of files
- if first_run.present?
  .form-inline
    .form-group
      = label_tag 'file_name', 'File'
      = select_tag 'file_name', options_for_select(file_name_options, selected: params[:file_name]), id: 'file_name', class: 'form-control', include_blank: '[Please select a file]'
      %a.btn.btn-primary#show_file_list_button Show
  %div{style: "margin-top: 20px;"}
  %table.table.table-condensed.table-hover.table-striped#files_list{:'data-source' => "#{_files_list_parameter_set_path(parameter_set.to_param, format: "json", file_name: params[:file_name])}"}
    %thead
      %tr
        - FilesListDatatable.header.each do |header|
          = raw(header)
    %tbody
- else
  %p There is no run yet.
:javascript
  $(function() {
    const oFilesTable = OACIS.datatables_for_files_table('#files_list');

    $('#show_file_list_button').on('click', function() {
      const param_set_path = "#{parameter_set_path(@param_set)}";
      if($('#file_name').val() == "#{params['file_name']}") {
        location.reload();
      } else {
        location.href = param_set_path + '?file_name=' + $('#file_name').val() + '#!tab-files';
      }
    });

    $('#files_list_length').after('#{link_to 'Download all', download_result_files_parameter_set_path(@param_set, file_name: params[:file_name]), class: "btn btn-primary #{'disabled' if params[:file_name].blank?}", style: 'margin-left: 10px'}');
  });

app/views/parameter_sets/_form.html.haml
- simulator = parameter_set.simulator
= form_for([simulator, parameter_set], html: {class: 'form-horizontal', :'data-cli-url' => _create_cli_simulator_parameter_sets_url(simulator) } ) do |f|
  = render partial: 'shared/error_messages', locals: {error_messages: parameter_set.errors.full_messages}
  = render partial: 'shared/error_messages', locals: {error_messages: run.errors.full_messages}
  - parameter_set.simulator.parameter_definitions.each do |pd|
    - key = pd.key
    - property = :"v[#{key}]"
    - value = parameter_set.v[key]
    .form-group
      = label_tag(property, "#{key} (#{pd.type})", class: 'col-md-2 control-label')
      .col-md-3
        - if pd.type == "Selection"
          = check_box_tag("v_#{key}_multi_toggle", "1", false, id: "v_#{key}_multi_toggle")
          = label_tag("v_#{key}_multi_toggle", "multiple selection")
          %br/
          = select_tag("v[#{key}][]", options_for_select(pd.options_array, selected: value), id: "v_#{key}_select", class: 'form-control', 'aria-describedby': "desc_#{key}")
          -# to make sure that the select_tag returns an array, the name must be "v[#{key}][]"
        - elsif pd.type == "Object"
          = text_area_tag(property, value.to_s, class: 'form-control', 'aria-describedby': "desc_#{key}", data: {html: 'true', toggle: 'tooltip', placement: 'bottom', 'original-title': "use JSON format"})
        - else
          = text_field_tag(property, value.to_s, class: 'form-control', 'aria-describedby': "desc_#{key}")
      .col-md-4
        %span{id: "desc_#{key}", class: "help-block"}
          = pd.description
  .form-group
    = label_tag('num_runs', 'Target # of Runs', class: 'col-md-2 control-label')
    .col-md-3
      = select_tag('num_runs', options_for_select([0,1,2,3,4,5,10,20,50,100], selected: (@num_runs || 1)), class: 'form-control')
  #runs_fields
    = fields_for run do |builder|
      = render 'runs/fields', run: builder.object, f: builder
  .form-group
    .col-md-2.col-md-offset-2
      = submit_tag "Create", class: 'btn btn-primary'
      = link_to "Cancel", simulator_path(simulator), class: 'btn btn-default'
  CLI command:
  %pre#cli-command

:javascript
  $(function() {
    const hide_show_runs_field = function () {
      if( $('#num_runs').val() == 0 ) {
        $('#runs_fields').find(':input').attr('disabled', true);
      }
      else {
        $('#runs_fields').find(':input').removeAttr('disabled');
      }
    }
    hide_show_runs_field();
    $('#num_runs').change(hide_show_runs_field);
  });

  $(function() {
    const show_cli_command = function() {
      const form = $('#new_parameter_set');
      $.get(form.data('cli-url'), form.serialize(), function(data) {
        $('#cli-command').text(data);
      });
    }
    $('#new_parameter_set').change(show_cli_command);
    show_cli_command();
  });

  $(function() {
    $('input[id$="_multi_toggle"]').change(function() {
      const selectId = this.id.replace('_multi_toggle', '_select');
      const $select = $('#' + selectId);

      if ($(this).is(':checked')) {
        $select.attr('multiple', 'multiple');
        $select.addClass('multi-select');
      } else {
        $select.removeAttr('multiple');
        $select.removeClass('multi-select');
      }
    });
  });

app/views/parameter_sets/_inner_table.html.haml
%div.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a{"href"=>"#tab-list-runs", "data-toggle" => "tab"} Runs
    %li
      %a{"href"=>"#tab-parameter-analyzers", "data-toggle" => "tab"} Analyses

  .tab-content
    .tab-pane.active#tab-list-runs
      = render "runs", parameter_set: parameter_set
    .tab-pane#tab-parameter-analyzers
      - if parameter_set.analyses.where(status: :finished).empty?
        No finished analysis is found.
      - else
        - parameter_set.analyses.where(status: :finished).each do |anl|
          %hr
          %h3= "Result of Analysis: #{anl.analyzer.name}"
          = link_to(anl.id,anl)
          - if anl.parameters.present?
            = render partial: "shared/parameters_table", locals: {parameters_hash: anl.parameters}
          = render partial: "shared/results", locals: {result: anl.result, result_paths: anl.result_paths, archived_result_path: anl.archived_result_path }

app/views/parameter_sets/_messages.html.haml
- if success_messages.present?
  #success_explanation
    %ul
      - success_messages.each do |msg|
        %li
          *
          = msg
- if error_messages.present?
  #error_explanation
    %ul
      - error_messages.each do |msg|
        %li
          *
          = msg

app/views/parameter_sets/_runs.html.haml
%div{style: "margin-top: 20px;"}
%table.table.table-condensed.table-hover.table-striped#runs_list{:'data-source' => "#{_runs_list_parameter_set_path(parameter_set.to_param, format: "json")}"}
  %thead
    %tr
      - RunsListDatatable.header.each do |header|
        = raw(header)
  %tbody

- if OACIS_ACCESS_LEVEL >= 1
  %h3 Create New Runs
  - run = parameter_set.runs.build(submitted_to: parameter_set.simulator.executable_on.first)
  = form_for( [parameter_set, run], html: {class: 'form-horizontal', remote: true}) do |f|
    #run_form_messages
    .form-group
      = label_tag('num_runs', '# of Runs', class: 'col-md-2 control-label')
      .col-md-3
        = select_tag('num_runs', options_for_select([1,2,3,4,5,10,20,50,100]), {class: 'form-control'})
    = render 'runs/fields', run: run, f: f
    .form-group
      .col-md-4.col-md-offset-2
        = submit_tag 'Preview', name: 'preview_button', class: 'btn', remote: true
        = f.submit(class: 'btn btn-primary')
  #script_preview_modal.modal.large.fade
    .modal-dialog.modal-vertical-centered
      .modal-content
        .modal-header
          %button.close{type: "button", "data-dismiss" => "modal"}
            &times;
          %h4.modal-title
            Job Script Preview
        .modal-body.large#script_preview
        .modal-footer
          %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
            Close

:javascript
  $(function() {
    const oRunsTable = OACIS.datatables_for_runs_table('#runs_list');
  });
  $(function() {
     $('#run_check_all').prop('checked', false);
  });

app/views/parameter_sets/show.html.haml
= render partial: "shared/breadcrumb", locals: {links: breadcrumb_links_for(@param_set)}

.page-header
  - param_string = @param_set.v.map {|key,val| "#{key}=#{val}" }.join(', ')
  %h1
    Parameter Set
    %small= "(#{param_string})"
  = "ID : #{@param_set.id}"
  %br
  = "data directory: #{@param_set.dir}"

%div.tabbable
  %ul.nav.nav-tabs
    %li
      %a{"href"=>"#tab-about", "data-toggle" => "tab"} About
    %li.active
      %a{"href"=>"#tab-list-runs", "data-toggle" => "tab"} Runs
    %li
      %a{"href"=>"#tab-list-analyses", "data-toggle" => "tab"} Analyses
    %li
      %a{"href"=>"#tab-plot", "data-toggle" => "tab"} Plot
    %li
      %a{"href"=>"#tab-files", "data-toggle" => "tab"} Files

  .tab-content
    .tab-pane#tab-about
      %div{style:"margin-top: 20px;"}
        - if OACIS_ACCESS_LEVEL >= 1
          = link_to("Duplicate", duplicate_parameter_set_path(@param_set), class: 'btn btn-primary')
          = link_to 'Delete', @param_set, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning'
        = link_to 'Show in JSON', parameter_set_path(@param_set, format: :json), class: 'btn btn-default'
      = render partial: "shared/parameters_table", locals: {parameters_hash: @param_set.v}
      = render "similar_parameter_sets_list", parameter_set: @param_set
    .tab-pane.active#tab-list-runs
      = render "runs", parameter_set: @param_set
    .tab-pane#tab-list-analyses
      = render "analyses", parameter_set: @param_set
    .tab-pane#tab-plot
      = render "plot", parameter_set: @param_set
    .tab-pane#tab-files
      = render "files", parameter_set: @param_set